# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykPruebas'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    additionalArguments: '--all-projects'
    

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykPruebas'
    testType: 'container'
    dockerImageName: 'Pruebas'
    monitorWhen: 'always'
    failOnIssues: true